### ISSUE TITLE
[suggestions]add ida pro plugins.

### ISSUE THREAD

**Issue by techbliss** [onethawt/idaplugins-list#22]
Hello guys
I see you have some of my tools in your collections, maybe add the python IDE i made for Ida pro, and some of my other plugins, would be nice to see them in your collection.

[**Ida pro script editor**](https://github.com/techbliss/Python_editor)

[**Free_the_Debuggers**](https://github.com/techbliss/Free_the_Debuggers)

[**Ida Pro Screen Recorder**](https://github.com/techbliss/Ida_Pro_Screen_Recorder)

[**Proccessor Changer**](https://github.com/techbliss/Processor-Changer)

Keep up the good work.

**Comment by onethawt** [comment]
Hi, been traveling. Will get to this in a few days. You are more than welcome to submit a PR.

**Comment by techbliss** [comment]
okay will do.
thx
