### ISSUE TITLE
Adding more plugins

### ISSUE THREAD

**Issue by CaledoniaProject** [onethawt/idaplugins-list#28]
The following plugins are hosted on github and have detailed documentations, can you add them to the list?

[https://github.com/comsecuris/gdbida](https://github.com/comsecuris/gdbida)
[https://github.com/Comsecuris/ida_strcluster](https://github.com/Comsecuris/ida_strcluster)
[https://github.com/1111joe1111/ida_ea](https://github.com/1111joe1111/ida_ea)
[https://github.com/gdelugre/ida-arm-system-highlight](https://github.com/gdelugre/ida-arm-system-highlight)
[https://github.com/darx0r/Reef](https://github.com/darx0r/Reef)
[https://github.com/ALSchwalm/dwarfexport](https://github.com/ALSchwalm/dwarfexport)
[https://github.com/maddiestone/IDAPythonEmbeddedToolkit](https://github.com/maddiestone/IDAPythonEmbeddedToolkit)
[https://github.com/polymorf/findcrypt-yara](https://github.com/polymorf/findcrypt-yara)

**Comment by onethawt** [comment]
Added.

**Comment by CaledoniaProject** [comment]
Thanks

**Comment by csersoft** [comment]
IDAPro HightLight Plugin
[https://github.com/RevSpBird/HightLight](https://github.com/RevSpBird/HightLight)
