### ISSUE TITLE
Suggestion to add MazeWalker

### ISSUE THREAD

**Issue by OhMyGodWhy** [onethawt/idaplugins-list#48]
Official description from https://github.com/0xPhoeniX/MazeWalker

> Toolkit for enriching and speeding up static malware analysis

Creates a prettier function overview:
 
![Prettify function window](https://github.com/0xPhoeniX/MazeWalker/raw/master/images/viz_tranz.png)

**Comment by onethawt** [comment]
Done and thanks.
